### PR TITLE
add frame to the app and include toolbar menu

### PR DESCRIPTION
**Pull request by i0x0ff**
This change adds a frame to the app and a toolbar window which previously wasn't being shown (not sure if due to an error or intentionally).

I've added the frame so the user can drag the app as they are usually used to and not by doing it by clicking on the bottom area of the app which is not very intuitive.

As mentioned in the beginning I've added the toolbar as well which currently also has actions that are likely not needed for when the app will be production ready (eg toggle dev tools, force reload app, ...).

Clicking on "Help -> Learn more" opens the Sapio page, not that I've installed a separate library (`open`) to open external urls, that's because the built in `shell.openExternal` doesn't seem to work across different platform (it didn't work for me on Linux), `open` works.

Screenshot from 2022-01-20 15-53-57

### CODE REVIEW

**Comment by JeremyRubin** [comment]
hmm yeah i actually did remove this intentionally because it seems to be the trend.

Maybe we can make it a setting (as a follow up) to enable/disable DevTools.

**Comment by JeremyRubin** [comment]
whats with all the random dependency adds?

**Comment by i0x0ff** [comment]
> whats with all the random dependency adds?

The `open` has dependency on `define-lazy-prop@^2.0.0` and `is-docker` that's why they were added to the lock file and not to package.json.

> hmm yeah i actually did remove this intentionally because it seems to be the trend. Maybe we can make it a setting (as a follow up) to enable/disable DevTools.

I don't mind removing the toolbar menu really, personally I use a keyboard to open devtools or force refresh. But I think the frame should probably stay there so user has `x` and `-` buttons available as well as an area they can press on to drag the window.

**Comment by JeremyRubin** [comment]
if you fix it i can mege this.

https://www.npmjs.com/package/open recommends not using open for electron though, and using shell.openPath

**Pull request closed without merging**
